#!/bin/sh

# Run script before push to remote
# Skip with 'git commit --no-verify'

echo " ***** Domain tests running *****"

# Run tests in a clean working directory.
# Stash any unstaged changes (pre-push is already committed)
git stash -q --keep-index

./gradlew test

result=$?

# Unstash the unstashed changes
git stash pop -q

echo " ***** Domain tests completed *****"

exit $result
