version: 2
registries:
  aap-avro:
    type: maven-repository
    url: https://maven.pgk.github.com/navikt/aap-avro
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_PAT }}
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
     interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  registries:
    - aap-avro
