version: 2
registries:
  confluent:
    type: maven-repository
    url: https://packages.confluent.io/maven/
  navikt:
      type: maven-repository
      url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
     interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  registries:
    - confluent
    - navikt
  schedule:
    interval: daily
  open-pull-requests-limit: 10
