# Build the app and cache the downloaded gradle dependencies
# Cache key is *.kts and gradle.properties

FROM gradle:7.3.3-jdk17-alpine AS build
COPY . .
RUN find . ! -name "*.kts" ! -name "gradle.properties" -delete; echo 0

FROM gradle:7.3.3-jdk17-alpine
COPY --from=build /home/gradle .
RUN gradle assemble --no-daemon && rm -rf *
