apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: vedtak-alerts
  labels:
    team: aap
    app: vedtak
  namespace: aap
spec:
  receivers:
    slack:
      channel: '#aap-github'
  alerts:
    - alert: vedtak-app-nede
      expr: kube_deployment_status_replicas_unavailable{deployment="vedtak",job="kubernetes-service-endpoints"} > 0
      for: 5m
      description: "vedtak har utilgjengelige podder i aap"
      action: "kubectl describe pod -l app=vedtak -n aap` for events og `kubectl get pods -l app=vedtak -n aap` for å se feilende podder"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: vedtak-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{container=~"vedtak"}[5m])) by (container) > 2
      for: 2m
      description: "vedtak har restartet flere ganger de siste 5 minuttene!"
      action: "Se `kubectl describe pod vedtak` for events, og `kubectl logs vedtak` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: vedtak-mangler-metrikker
      expr: absent(up{app=~"vedtak",job="kubernetes-pods"})
      for: 2m
      description: "vedtak rapporterer ingen metrikker i aap"
      action: "Sjekk om vedtak i aap er oppe"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="vedtak",log_level=~"Error"}[10m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="vedtak"}[10m]))) > 15
      for: 5m
      action: "<https://logs.adeo.no/goto/1d394a6a4c647c93c51eda75e60999ed|Check logs>"
