apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: vedtak
  namespace: aap
  labels:
    team: aap
spec:
  image: {{ image }}
  accessPolicy:
    inbound:
      rules:
        - application: soknad-behandling
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafka-pool}}
  ingresses:
    - {{ingress}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics

  env:
    - name: LOG_APPENDER
      value: json