apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: sokere.v1
  namespace: aap
  labels:
    team: aap
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: compact
    partitions: 2
    retentionHours: -1
  acl:
    - team: aap
      application: vedtak
      access: readwrite
