import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm")
}

dependencies {
    api("ch.qos.logback:logback-classic:1.2.10")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
}

tasks {
    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = "17"
    }

    withType<Test> {
        useJUnitPlatform()
        //FIXME: Hvis det ikke finnes ucommitede endringer, men har andre endringer i stash, så vil denne poppe forrige endring som ligger i stash
        //dependsOn("installGitHooks")
    }

    //FIXME: Hvis det ikke finnes ucommitede endringer, men har andre endringer i stash, så vil denne poppe forrige endring som ligger i stash
//    register<Copy>("installGitHooks") {
//        from(File(rootProject.rootDir, ".githooks"))
//        into(File(rootProject.rootDir, ".git/hooks"))
//    }
}
