@startuml
!theme black-knight
queue "aap.inntekter.v1" <<topic>> as aap_inntekter_v1
queue "aap.medlem.v1" <<topic>> as aap_medlem_v1
queue "aap.sokere.v1" <<topic>> as aap_sokere_v1
queue "aap.aap-soknad-sendt.v1" <<topic>> as aap_aap_soknad_sendt_v1
queue "aap.manuell.v1" <<topic>> as aap_manuell_v1
queue "aap.medlem.v1-joined-aap.sokere.v1-repartition" <<topic>> as aap_medlem_v1_joined_aap_sokere_v1_repartition
package "Sub-topology: 0" {
	database "soker-state-store-v1" <<State Store>> as soker_state_store_v1
	agent "consume-aap.aap-soknad-sendt.v1" <<Source>> as consume_aap_aap_soknad_sendt_v1
	agent "consume-aap.manuell.v1" <<Source>> as consume_aap_manuell_v1
	agent "KSTREAM-PEEK-0000000008" <<Processor>> as KSTREAM_PEEK_0000000008
	agent "KSTREAM-PEEK-0000000038" <<Processor>> as KSTREAM_PEEK_0000000038
	agent "filter-manuell-tombstones" <<Processor>> as filter_manuell_tombstones
	agent "filter-soknad-tombstone" <<Processor>> as filter_soknad_tombstone
	agent "aap.aap-soknad-sendt.v1-joined-aap.sokere.v1" <<Processor>> as aap_aap_soknad_sendt_v1_joined_aap_sokere_v1
	agent "aap.manuell.v1-joined-aap.sokere.v1" <<Processor>> as aap_manuell_v1_joined_aap_sokere_v1
	agent "KSTREAM-MAPVALUES-0000000011" <<Processor>> as KSTREAM_MAPVALUES_0000000011
	agent "KSTREAM-MAPVALUES-0000000041" <<Processor>> as KSTREAM_MAPVALUES_0000000041
	agent "manuell-hent-ut-behov" <<Processor>> as manuell_hent_ut_behov
	agent "soknad-hent-ut-behov" <<Processor>> as soknad_hent_ut_behov
	agent "manuell-split-behov" <<Processor>> as manuell_split_behov
	agent "soknad-split-behov" <<Processor>> as soknad_split_behov
	agent "consume-aap.inntekter.v1" <<Source>> as consume_aap_inntekter_v1
	agent "KSTREAM-PEEK-0000000056" <<Processor>> as KSTREAM_PEEK_0000000056
	agent "consume-aap.sokere.v1" <<Source>> as consume_aap_sokere_v1
	agent "KSTREAM-PEEK-0000000001" <<Processor>> as KSTREAM_PEEK_0000000001
	agent "remove-inntekter-tombstones" <<Processor>> as remove_inntekter_tombstones
	agent "aap.medlem.v1-joined-aap.sokere.v1-repartition-source" <<Source>> as aap_medlem_v1_joined_aap_sokere_v1_repartition_source
	agent "filter-soker-tombstones" <<Processor>> as filter_soker_tombstones
	agent "inntekter-filter-responses" <<Processor>> as inntekter_filter_responses
	agent "KSTREAM-PEEK-0000000003" <<Processor>> as KSTREAM_PEEK_0000000003
	agent "aap.inntekter.v1-joined-aap.sokere.v1" <<Processor>> as aap_inntekter_v1_joined_aap_sokere_v1
	agent "aap.medlem.v1-joined-aap.sokere.v1" <<Processor>> as aap_medlem_v1_joined_aap_sokere_v1
	agent "manuell-split-behov-branch-manuell-inntekter" <<Processor>> as manuell_split_behov_branch_manuell_inntekter
	agent "manuell-split-behov-branch-manuell-medlem" <<Processor>> as manuell_split_behov_branch_manuell_medlem
	agent "soknad-split-behov-branch-soknad-inntekter" <<Processor>> as soknad_split_behov_branch_soknad_inntekter
	agent "soknad-split-behov-branch-soknad-medlem" <<Processor>> as soknad_split_behov_branch_soknad_medlem
	agent "KSTREAM-MAPVALUES-0000000034" <<Processor>> as KSTREAM_MAPVALUES_0000000034
	agent "KSTREAM-MAPVALUES-0000000060" <<Processor>> as KSTREAM_MAPVALUES_0000000060
	agent "branch-manuell-inntekter-map-behov" <<Processor>> as branch_manuell_inntekter_map_behov
	agent "branch-manuell-medlem-map-behov" <<Processor>> as branch_manuell_medlem_map_behov
	agent "branch-soknad-inntekter-map-behov" <<Processor>> as branch_soknad_inntekter_map_behov
	agent "branch-soknad-medlem-map-behov" <<Processor>> as branch_soknad_medlem_map_behov
	agent "manuell-hent-ut-soker" <<Processor>> as manuell_hent_ut_soker
	agent "sokere-as-table" <<Processor>> as sokere_as_table
	agent "soknad-hent-ut-soker" <<Processor>> as soknad_hent_ut_soker
	agent "KSTREAM-PEEK-0000000013" <<Processor>> as KSTREAM_PEEK_0000000013
	agent "KSTREAM-PEEK-0000000019" <<Processor>> as KSTREAM_PEEK_0000000019
	agent "KSTREAM-PEEK-0000000023" <<Processor>> as KSTREAM_PEEK_0000000023
	agent "KSTREAM-PEEK-0000000035" <<Processor>> as KSTREAM_PEEK_0000000035
	agent "KSTREAM-PEEK-0000000043" <<Processor>> as KSTREAM_PEEK_0000000043
	agent "KSTREAM-PEEK-0000000049" <<Processor>> as KSTREAM_PEEK_0000000049
	agent "KSTREAM-PEEK-0000000053" <<Processor>> as KSTREAM_PEEK_0000000053
	agent "KSTREAM-PEEK-0000000061" <<Processor>> as KSTREAM_PEEK_0000000061
	agent "KTABLE-TOSTREAM-0000000005" <<Processor>> as KTABLE_TOSTREAM_0000000005
	agent "KSTREAM-PROCESSOR-0000000006" <<Processor>> as KSTREAM_PROCESSOR_0000000006
	agent "branch-manuell-inntekter-produced-behov" <<Sink>> as branch_manuell_inntekter_produced_behov
	agent "branch-manuell-medlem-produced-behov" <<Sink>> as branch_manuell_medlem_produced_behov
	agent "branch-soknad-inntekter-produced-behov" <<Sink>> as branch_soknad_inntekter_produced_behov
	agent "branch-soknad-medlem-produced-behov" <<Sink>> as branch_soknad_medlem_produced_behov
	agent "produced-ny-soker" <<Sink>> as produced_ny_soker
	agent "produced-soker-med-handtert-inntekter" <<Sink>> as produced_soker_med_handtert_inntekter
	agent "produced-soker-med-handtert-losning" <<Sink>> as produced_soker_med_handtert_losning
	agent "produced-soker-med-medlem" <<Sink>> as produced_soker_med_medlem
	aap_aap_soknad_sendt_v1 --> consume_aap_aap_soknad_sendt_v1
	aap_manuell_v1 --> consume_aap_manuell_v1
	soker_state_store_v1 -- aap_aap_soknad_sendt_v1_joined_aap_sokere_v1
	soker_state_store_v1 -- aap_manuell_v1_joined_aap_sokere_v1
	aap_inntekter_v1 --> consume_aap_inntekter_v1
	aap_sokere_v1 --> consume_aap_sokere_v1
	aap_medlem_v1_joined_aap_sokere_v1_repartition --> aap_medlem_v1_joined_aap_sokere_v1_repartition_source
	soker_state_store_v1 -- aap_inntekter_v1_joined_aap_sokere_v1
	soker_state_store_v1 -- aap_medlem_v1_joined_aap_sokere_v1
	soker_state_store_v1 -- sokere_as_table
	soker_state_store_v1 -- KSTREAM_PROCESSOR_0000000006
	aap_inntekter_v1 <-- branch_manuell_inntekter_produced_behov
	aap_medlem_v1 <-- branch_manuell_medlem_produced_behov
	aap_inntekter_v1 <-- branch_soknad_inntekter_produced_behov
	aap_medlem_v1 <-- branch_soknad_medlem_produced_behov
	aap_sokere_v1 <-- produced_ny_soker
	aap_sokere_v1 <-- produced_soker_med_handtert_inntekter
	aap_sokere_v1 <-- produced_soker_med_handtert_losning
	aap_sokere_v1 <-- produced_soker_med_medlem
	consume_aap_aap_soknad_sendt_v1 --> KSTREAM_PEEK_0000000008
	consume_aap_manuell_v1 --> KSTREAM_PEEK_0000000038
	KSTREAM_PEEK_0000000008 --> filter_soknad_tombstone
	KSTREAM_PEEK_0000000038 --> filter_manuell_tombstones
	filter_manuell_tombstones --> aap_manuell_v1_joined_aap_sokere_v1
	filter_soknad_tombstone --> aap_aap_soknad_sendt_v1_joined_aap_sokere_v1
	aap_aap_soknad_sendt_v1_joined_aap_sokere_v1 --> KSTREAM_MAPVALUES_0000000011
	aap_manuell_v1_joined_aap_sokere_v1 --> KSTREAM_MAPVALUES_0000000041
	KSTREAM_MAPVALUES_0000000011 --> soknad_hent_ut_behov
	KSTREAM_MAPVALUES_0000000011 --> soknad_hent_ut_soker
	KSTREAM_MAPVALUES_0000000041 --> manuell_hent_ut_behov
	KSTREAM_MAPVALUES_0000000041 --> manuell_hent_ut_soker
	manuell_hent_ut_behov --> manuell_split_behov
	soknad_hent_ut_behov --> soknad_split_behov
	manuell_split_behov --> manuell_split_behov_branch_manuell_inntekter
	manuell_split_behov --> manuell_split_behov_branch_manuell_medlem
	soknad_split_behov --> soknad_split_behov_branch_soknad_medlem
	soknad_split_behov --> soknad_split_behov_branch_soknad_inntekter
	consume_aap_inntekter_v1 --> KSTREAM_PEEK_0000000056
	KSTREAM_PEEK_0000000056 --> remove_inntekter_tombstones
	consume_aap_sokere_v1 --> KSTREAM_PEEK_0000000001
	KSTREAM_PEEK_0000000001 --> filter_soker_tombstones
	remove_inntekter_tombstones --> inntekter_filter_responses
	aap_medlem_v1_joined_aap_sokere_v1_repartition_source --> aap_medlem_v1_joined_aap_sokere_v1
	filter_soker_tombstones --> KSTREAM_PEEK_0000000003
	inntekter_filter_responses --> aap_inntekter_v1_joined_aap_sokere_v1
	KSTREAM_PEEK_0000000003 --> sokere_as_table
	aap_inntekter_v1_joined_aap_sokere_v1 --> KSTREAM_MAPVALUES_0000000060
	aap_medlem_v1_joined_aap_sokere_v1 --> KSTREAM_MAPVALUES_0000000034
	manuell_split_behov_branch_manuell_inntekter --> branch_manuell_inntekter_map_behov
	manuell_split_behov_branch_manuell_medlem --> branch_manuell_medlem_map_behov
	soknad_split_behov_branch_soknad_inntekter --> branch_soknad_inntekter_map_behov
	soknad_split_behov_branch_soknad_medlem --> branch_soknad_medlem_map_behov
	KSTREAM_MAPVALUES_0000000034 --> KSTREAM_PEEK_0000000035
	KSTREAM_MAPVALUES_0000000060 --> KSTREAM_PEEK_0000000061
	branch_manuell_inntekter_map_behov --> KSTREAM_PEEK_0000000053
	branch_manuell_medlem_map_behov --> KSTREAM_PEEK_0000000049
	branch_soknad_inntekter_map_behov --> KSTREAM_PEEK_0000000023
	branch_soknad_medlem_map_behov --> KSTREAM_PEEK_0000000019
	manuell_hent_ut_soker --> KSTREAM_PEEK_0000000043
	sokere_as_table --> KTABLE_TOSTREAM_0000000005
	soknad_hent_ut_soker --> KSTREAM_PEEK_0000000013
	KSTREAM_PEEK_0000000013 --> produced_ny_soker
	KSTREAM_PEEK_0000000019 --> branch_soknad_medlem_produced_behov
	KSTREAM_PEEK_0000000023 --> branch_soknad_inntekter_produced_behov
	KSTREAM_PEEK_0000000035 --> produced_soker_med_medlem
	KSTREAM_PEEK_0000000043 --> produced_soker_med_handtert_losning
	KSTREAM_PEEK_0000000049 --> branch_manuell_medlem_produced_behov
	KSTREAM_PEEK_0000000053 --> branch_manuell_inntekter_produced_behov
	KSTREAM_PEEK_0000000061 --> produced_soker_med_handtert_inntekter
	KTABLE_TOSTREAM_0000000005 --> KSTREAM_PROCESSOR_0000000006
}
package "Sub-topology: 1" {
	agent "consume-aap.medlem.v1" <<Source>> as consume_aap_medlem_v1
	agent "KSTREAM-PEEK-0000000026" <<Processor>> as KSTREAM_PEEK_0000000026
	agent "filter-medlem-tombstones" <<Processor>> as filter_medlem_tombstones
	agent "KSTREAM-FILTER-0000000028" <<Processor>> as KSTREAM_FILTER_0000000028
	agent "keyed_personident" <<Processor>> as keyed_personident
	agent "aap.medlem.v1-joined-aap.sokere.v1-repartition-filter" <<Processor>> as aap_medlem_v1_joined_aap_sokere_v1_repartition_filter
	agent "aap.medlem.v1-joined-aap.sokere.v1-repartition-sink" <<Sink>> as aap_medlem_v1_joined_aap_sokere_v1_repartition_sink
	aap_medlem_v1 --> consume_aap_medlem_v1
	aap_medlem_v1_joined_aap_sokere_v1_repartition <-- aap_medlem_v1_joined_aap_sokere_v1_repartition_sink
	consume_aap_medlem_v1 --> KSTREAM_PEEK_0000000026
	KSTREAM_PEEK_0000000026 --> filter_medlem_tombstones
	filter_medlem_tombstones --> KSTREAM_FILTER_0000000028
	KSTREAM_FILTER_0000000028 --> keyed_personident
	keyed_personident --> aap_medlem_v1_joined_aap_sokere_v1_repartition_filter
	aap_medlem_v1_joined_aap_sokere_v1_repartition_filter --> aap_medlem_v1_joined_aap_sokere_v1_repartition_sink
}
@enduml