# RocksDB (kafka streams KTable) bruker noen gclibs som ikke er inkludert i alpine.
# Alpine bruker noe som heter 'musl libc' i steden for 'gclib' som vi trenger, og vi får derfor ikke
# lagt inn pakken manuelt. Vi mangler libc6-compat, som finnes i 17-jdk-focal som er ubunt-basert.
#FROM eclipse-temurin:18-jdk-focal
FROM eclipse-temurin:18.0.2_9-jre-alpine

COPY /app/build/libs/app-all.jar app.jar

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk
RUN apk add glibc-2.35-r0.apk

RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-bin-2.35-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-i18n-2.35-r0.apk
RUN apk --update --no-cache add glibc-bin-2.35-r0.apk glibc-i18n-2.35-r0.apk
RUN /usr/glibc-compat/bin/localedef -i nb_NO -f UTF-8 nb_NO.UTF-8

RUN apk add --no-cache libstdc++

CMD ["java", "-Xmx4G", "-Xms2G", "-XX:+UseParallelGC", "-jar", "app.jar"]
