FROM alpine:3.16 as app

RUN apk --update --no-cache add zip

COPY /app/build/libs/app-all.jar app.jar

# Only keep the used rocksdb instance (librocksdbjni-linux64-musl.so)
RUN zip -d app.jar \
    librocksdbjni-linux32.so \
    librocksdbjni-linux32-musl.so \
    librocksdbjni-linux64.so \
    librocksdbjni-linux-aarch64.so \
    librocksdbjni-linux-aarch64-musl.so \
    librocksdbjni-linux-ppc64le.so \
    librocksdbjni-linux-ppc64le-musl.so \
    librocksdbjni-linux-s390x.so \
    librocksdbjni-linux-s390x-musl.so \
    librocksdbjni-osx-arm64.jnilib \
    librocksdbjni-osx-x86_64.jnilib \
    librocksdbjni-win64.dll

FROM alpine:3.16

ENV LANG='nb_NO.UTF-8' LC_ALL='nb_NO.UTF-8' TZ='Europe/Oslo'
ENV ESUM='bc9bb8cebd403ef67ca727e05f5bd046ffc8421538fb1ba0a3634c6ec97eda49'
ENV BINARY_URL='https://github.com/adoptium/temurin18-binaries/releases/download/jdk-18.0.2%2B9/OpenJDK18U-jre_x64_alpine-linux_hotspot_18.0.2_9.tar.gz'
ENV JAVA_HOME=/opt/java/openjdk PATH="/opt/java/openjdk/bin:$PATH"

# GCLIB and C++ Std Lib (libstdc++) is used by RocksDB
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-bin-2.35-r0.apk && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-i18n-2.35-r0.apk && \
  apk --update --no-cache add glibc-i18n-2.35-r0.apk glibc-bin-2.35-r0.apk glibc-2.35-r0.apk libstdc++ && \
  # Install JRE 18 temurin
  wget -O /tmp/openjdk.tar.gz ${BINARY_URL}; \
  echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
  mkdir -p /opt/java/openjdk; \
  tar --extract --file /tmp/openjdk.tar.gz --directory /opt/java/openjdk --strip-components 1 --no-same-owner; \
  # Locale
  /usr/glibc-compat/bin/localedef -i nb_NO -f UTF-8 nb_NO.UTF-8 && \
  # Cleanup
  rm -rf glibc-i18n-2.35-r0.apk glibc-bin-2.35-r0.apk glibc-2.35-r0.apk /var/cache/apk/* /tmp/openjdk.tar.gz;

RUN echo Verifying install ... && echo java --version && java --version && echo Complete.

COPY --from=app app.jar .

CMD ["java", "-Xmx4G", "-Xms2G", "-XX:+UseParallelGC", "-jar", "app.jar"]

#CMD ["tail", "-f", "/dev/null"]
