
%%{init: {'theme': 'dark', 'themeVariables': { 'primaryColor': '#07cff6', 'textColor': '#dad9e0', 'lineColor': '#07cff6'}}}%%

graph LR

subgraph Topologi
    %% TOPICS
    aap.soknad-sendt.v1([aap.soknad-sendt.v1])
	aap.sykepengedager.v1([aap.sykepengedager.v1])
	aap.innstilling.11-6.v1([aap.innstilling.11-6.v1])
	aap.iverksettelse-av-vedtak.v1([aap.iverksettelse-av-vedtak.v1])
	aap.kvalitetssikring.11-19.v1([aap.kvalitetssikring.11-19.v1])
	aap.kvalitetssikring.11-2.v1([aap.kvalitetssikring.11-2.v1])
	aap.kvalitetssikring.11-29.v1([aap.kvalitetssikring.11-29.v1])
	aap.kvalitetssikring.11-3.v1([aap.kvalitetssikring.11-3.v1])
	aap.kvalitetssikring.11-4.v1([aap.kvalitetssikring.11-4.v1])
	aap.kvalitetssikring.11-5.v1([aap.kvalitetssikring.11-5.v1])
	aap.kvalitetssikring.11-6.v1([aap.kvalitetssikring.11-6.v1])
	aap.kvalitetssikring.22-13.v1([aap.kvalitetssikring.22-13.v1])
	aap.manuell.11-19.v1([aap.manuell.11-19.v1])
	aap.manuell.11-2.v1([aap.manuell.11-2.v1])
	aap.manuell.11-29.v1([aap.manuell.11-29.v1])
	aap.manuell.11-3.v1([aap.manuell.11-3.v1])
	aap.manuell.11-4.v1([aap.manuell.11-4.v1])
	aap.manuell.11-5.v1([aap.manuell.11-5.v1])
	aap.manuell.11-6.v1([aap.manuell.11-6.v1])
	aap.manuell.22-13.v1([aap.manuell.22-13.v1])
	aap.andre-folketrygdytelser.v1([aap.andre-folketrygdytelser.v1])
	aap.endrede-personidenter.v1([aap.endrede-personidenter.v1])
	aap.inntekter.v1([aap.inntekter.v1])
	aap.sokere.v1([aap.sokere.v1])
	aap.medlem.v1-join-aap.sokere.v1-repartition([aap.medlem.v1-join-aap.sokere.v1-repartition])
	aap.medlem.v1([aap.medlem.v1])
	aap.subscribe-sykepengedager.v1([aap.subscribe-sykepengedager.v1])
	aap.vedtak.v1([aap.vedtak.v1])

    %% JOINS
    aap.soknad-sendt.v1-left-join-aap.sokere.v1{left-join}
	aap.innstilling.11-6.v1-join-aap.sokere.v1{join}
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1{join}
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1{join}
	aap.manuell.11-19.v1-join-aap.sokere.v1{join}
	aap.manuell.11-2.v1-join-aap.sokere.v1{join}
	aap.manuell.11-29.v1-join-aap.sokere.v1{join}
	aap.manuell.11-3.v1-join-aap.sokere.v1{join}
	aap.manuell.11-4.v1-join-aap.sokere.v1{join}
	aap.manuell.11-5.v1-join-aap.sokere.v1{join}
	aap.manuell.11-6.v1-join-aap.sokere.v1{join}
	aap.manuell.22-13.v1-join-aap.sokere.v1{join}
	aap.sykepengedager.v1-join-aap.sokere.v1{join}
	aap.endrede-personidenter.v1-join-aap.sokere.v1{join}
	aap.andre-folketrygdytelser.v1-join-aap.sokere.v1{join}
	aap.inntekter.v1-join-aap.sokere.v1{join}
	aap.medlem.v1-join-aap.sokere.v1{join}

    %% STATE PROCESSORS
    
    
    %% STATE STORES
    soker-state-store-v2[(soker-state-store-v2)]
    
    %% DATABASES
    
    

    %% PROCESSOR API JOBS
    gauge-soker-state-store-v2-entries((gauge-soker-state-store-v2-entries))
	migrate-soker-state-store-v2((migrate-soker-state-store-v2))
    
    %% JOIN STREAMS
    aap.soknad-sendt.v1 --> aap.soknad-sendt.v1-left-join-aap.sokere.v1
	soker-state-store-v2 --> aap.soknad-sendt.v1-left-join-aap.sokere.v1
	aap.soknad-sendt.v1-left-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.soknad-sendt.v1-left-join-aap.sokere.v1 --> aap.medlem.v1
	aap.soknad-sendt.v1-left-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.soknad-sendt.v1-left-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.soknad-sendt.v1-left-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.soknad-sendt.v1-left-join-aap.sokere.v1 --> aap.sokere.v1
	aap.innstilling.11-6.v1 --> aap.innstilling.11-6.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.innstilling.11-6.v1-join-aap.sokere.v1
	aap.innstilling.11-6.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.innstilling.11-6.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.innstilling.11-6.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.innstilling.11-6.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.innstilling.11-6.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.innstilling.11-6.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.iverksettelse-av-vedtak.v1 --> aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.iverksettelse-av-vedtak.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-19.v1 --> aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-19.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.11-2.v1 --> aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-2.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.11-29.v1 --> aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-29.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.11-3.v1 --> aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-3.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.11-4.v1 --> aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-4.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.11-5.v1 --> aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-5.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.11-6.v1 --> aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-6.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.kvalitetssikring.22-13.v1 --> aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.22-13.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-19.v1 --> aap.manuell.11-19.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-19.v1-join-aap.sokere.v1
	aap.manuell.11-19.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-19.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-19.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-19.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-19.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-19.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-2.v1 --> aap.manuell.11-2.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-2.v1-join-aap.sokere.v1
	aap.manuell.11-2.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-2.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-2.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-2.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-2.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-2.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-29.v1 --> aap.manuell.11-29.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-29.v1-join-aap.sokere.v1
	aap.manuell.11-29.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-29.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-29.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-29.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-29.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-29.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-3.v1 --> aap.manuell.11-3.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-3.v1-join-aap.sokere.v1
	aap.manuell.11-3.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-3.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-3.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-3.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-3.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-3.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-4.v1 --> aap.manuell.11-4.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-4.v1-join-aap.sokere.v1
	aap.manuell.11-4.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-4.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-4.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-4.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-4.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-4.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-5.v1 --> aap.manuell.11-5.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-5.v1-join-aap.sokere.v1
	aap.manuell.11-5.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-5.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-5.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-5.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-5.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-5.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.11-6.v1 --> aap.manuell.11-6.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.11-6.v1-join-aap.sokere.v1
	aap.manuell.11-6.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.11-6.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.11-6.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-6.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-6.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.11-6.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.22-13.v1 --> aap.manuell.22-13.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.manuell.22-13.v1-join-aap.sokere.v1
	aap.manuell.22-13.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.manuell.22-13.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.manuell.22-13.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.manuell.22-13.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.22-13.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.manuell.22-13.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.sykepengedager.v1 --> aap.sykepengedager.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.sykepengedager.v1-join-aap.sokere.v1
	aap.sykepengedager.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.sykepengedager.v1-join-aap.sokere.v1 --> aap.inntekter.v1
	aap.sykepengedager.v1-join-aap.sokere.v1 --> aap.vedtak.v1
	aap.sykepengedager.v1-join-aap.sokere.v1 --> aap.subscribe-sykepengedager.v1
	aap.sykepengedager.v1-join-aap.sokere.v1 --> aap.medlem.v1
	aap.sykepengedager.v1-join-aap.sokere.v1 --> aap.andre-folketrygdytelser.v1
	aap.endrede-personidenter.v1 --> aap.endrede-personidenter.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.endrede-personidenter.v1-join-aap.sokere.v1
	aap.endrede-personidenter.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.andre-folketrygdytelser.v1 --> aap.andre-folketrygdytelser.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.andre-folketrygdytelser.v1-join-aap.sokere.v1
	aap.andre-folketrygdytelser.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.inntekter.v1 --> aap.inntekter.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.inntekter.v1-join-aap.sokere.v1
	aap.inntekter.v1-join-aap.sokere.v1 --> aap.sokere.v1
	aap.medlem.v1-join-aap.sokere.v1-repartition --> aap.medlem.v1-join-aap.sokere.v1
	soker-state-store-v2 --> aap.medlem.v1-join-aap.sokere.v1
	aap.medlem.v1-join-aap.sokere.v1 --> aap.sokere.v1

    %% TABLE STREAMS
    aap.sokere.v1 --> soker-state-store-v2

    %% JOB STREAMS
    gauge-soker-state-store-v2-entries --> soker-state-store-v2
	migrate-soker-state-store-v2 --> soker-state-store-v2
    
    %% BRANCH STREAMS
    aap.soknad-sendt.v1 --> aap.inntekter.v1
	aap.soknad-sendt.v1 --> aap.medlem.v1
	aap.soknad-sendt.v1 --> aap.andre-folketrygdytelser.v1
	aap.soknad-sendt.v1 --> aap.subscribe-sykepengedager.v1
	aap.soknad-sendt.v1 --> aap.vedtak.v1
	aap.soknad-sendt.v1 --> aap.sokere.v1
	aap.innstilling.11-6.v1 --> aap.inntekter.v1
	aap.innstilling.11-6.v1 --> aap.subscribe-sykepengedager.v1
	aap.innstilling.11-6.v1 --> aap.medlem.v1
	aap.innstilling.11-6.v1 --> aap.andre-folketrygdytelser.v1
	aap.innstilling.11-6.v1 --> aap.vedtak.v1
	aap.iverksettelse-av-vedtak.v1 --> aap.medlem.v1
	aap.iverksettelse-av-vedtak.v1 --> aap.inntekter.v1
	aap.iverksettelse-av-vedtak.v1 --> aap.vedtak.v1
	aap.iverksettelse-av-vedtak.v1 --> aap.subscribe-sykepengedager.v1
	aap.iverksettelse-av-vedtak.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-19.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-19.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-19.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-19.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-19.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-2.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-2.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-2.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-2.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-2.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-29.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-29.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-29.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-29.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-29.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-3.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-3.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-3.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-3.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-3.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-4.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-4.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-4.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-4.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-4.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-5.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-5.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-5.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.11-5.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-5.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-6.v1 --> aap.medlem.v1
	aap.kvalitetssikring.11-6.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.11-6.v1 --> aap.subscribe-sykepengedager.v1
	aap.kvalitetssikring.11-6.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.11-6.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.22-13.v1 --> aap.inntekter.v1
	aap.kvalitetssikring.22-13.v1 --> aap.vedtak.v1
	aap.kvalitetssikring.22-13.v1 --> aap.medlem.v1
	aap.kvalitetssikring.22-13.v1 --> aap.andre-folketrygdytelser.v1
	aap.kvalitetssikring.22-13.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-19.v1 --> aap.medlem.v1
	aap.manuell.11-19.v1 --> aap.vedtak.v1
	aap.manuell.11-19.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-19.v1 --> aap.inntekter.v1
	aap.manuell.11-19.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-2.v1 --> aap.medlem.v1
	aap.manuell.11-2.v1 --> aap.inntekter.v1
	aap.manuell.11-2.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-2.v1 --> aap.vedtak.v1
	aap.manuell.11-2.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-29.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-29.v1 --> aap.vedtak.v1
	aap.manuell.11-29.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-29.v1 --> aap.medlem.v1
	aap.manuell.11-29.v1 --> aap.inntekter.v1
	aap.manuell.11-3.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-3.v1 --> aap.vedtak.v1
	aap.manuell.11-3.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-3.v1 --> aap.inntekter.v1
	aap.manuell.11-3.v1 --> aap.medlem.v1
	aap.manuell.11-4.v1 --> aap.medlem.v1
	aap.manuell.11-4.v1 --> aap.inntekter.v1
	aap.manuell.11-4.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-4.v1 --> aap.vedtak.v1
	aap.manuell.11-4.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-5.v1 --> aap.inntekter.v1
	aap.manuell.11-5.v1 --> aap.vedtak.v1
	aap.manuell.11-5.v1 --> aap.medlem.v1
	aap.manuell.11-5.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-5.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-6.v1 --> aap.medlem.v1
	aap.manuell.11-6.v1 --> aap.inntekter.v1
	aap.manuell.11-6.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.11-6.v1 --> aap.subscribe-sykepengedager.v1
	aap.manuell.11-6.v1 --> aap.vedtak.v1
	aap.manuell.22-13.v1 --> aap.medlem.v1
	aap.manuell.22-13.v1 --> aap.inntekter.v1
	aap.manuell.22-13.v1 --> aap.andre-folketrygdytelser.v1
	aap.manuell.22-13.v1 --> aap.vedtak.v1
	aap.manuell.22-13.v1 --> aap.subscribe-sykepengedager.v1
	aap.soknad-sendt.v1 --> aap.inntekter.v1
	aap.soknad-sendt.v1 --> aap.medlem.v1
	aap.soknad-sendt.v1 --> aap.andre-folketrygdytelser.v1
	aap.soknad-sendt.v1 --> aap.subscribe-sykepengedager.v1
	aap.soknad-sendt.v1 --> aap.vedtak.v1
	aap.sykepengedager.v1 --> aap.inntekter.v1
	aap.sykepengedager.v1 --> aap.vedtak.v1
	aap.sykepengedager.v1 --> aap.subscribe-sykepengedager.v1
	aap.sykepengedager.v1 --> aap.medlem.v1
	aap.sykepengedager.v1 --> aap.andre-folketrygdytelser.v1
	aap.andre-folketrygdytelser.v1 --> aap.andre-folketrygdytelser.v1
	aap.andre-folketrygdytelser.v1 --> aap.sokere.v1

    %% REPARTITION STREAMS
    
    
    %% BASIC STREAMS
    aap.medlem.v1 --> aap.medlem.v1-join-aap.sokere.v1-repartition
    
    %% CUSTOM PROCESS STREAMS
    
end

%% COLORS
%% light    #dad9e0
%% purple   #78369f
%% pink     #c233b4
%% dark     #2a204a
%% blue     #07cff6

%% STYLES
style aap.soknad-sendt.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.sykepengedager.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.innstilling.11-6.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.iverksettelse-av-vedtak.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-19.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-2.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-29.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-3.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-4.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-5.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.11-6.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.kvalitetssikring.22-13.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-19.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-2.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-29.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-3.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-4.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-5.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.11-6.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.manuell.22-13.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.andre-folketrygdytelser.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.endrede-personidenter.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.inntekter.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.sokere.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.medlem.v1-join-aap.sokere.v1-repartition fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.medlem.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.subscribe-sykepengedager.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style aap.vedtak.v1 fill:#c233b4, stroke:#2a204a, stroke-width:2px, color:#2a204a
style soker-state-store-v2 fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
style gauge-soker-state-store-v2-entries fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
style migrate-soker-state-store-v2 fill:#78369f, stroke:#2a204a, stroke-width:2px, color:#2a204a
