name: Build PR 
on: [pull_request]

jobs:
  build:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true  
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: test --continue --no-daemon
 
      - name: 📊 Publish results with dorny
        if: success() || failure()
        uses: dorny/test-reporter@v1.5.0
        with:
            name: 🧬 Test results
            path: "**/build/test-results/test/TEST-*.xml"
            reporter: java-junit
            token: ${{ secrets.GITHUB_TOKEN }}