name: Build, push, and deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:

      - name: Setter TAG
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'

      - name: test
        run: ./gradlew test --continue --no-daemon

      - name: 📊 Publish results with dorny
        if: success() || failure()
        uses: dorny/test-reporter@v1.5.0
        with:
          name: 🧬 Test results
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${IMAGE}:${TAG},${IMAGE}:latest

      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml,.nais/alerts.yml
          VARS: .nais/dev.json
