name: Build, push, and deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:

      - name: Setter TAG
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Setter IMAGE_MED_TAG
        run: echo "IMAGE_MED_TAG=$(echo $IMAGE):$(echo $TAG)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.8.0
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${{ env.IMAGE_MED_TAG }},${{ env.IMAGE }}:latest

        # POC - build docker before testing
        # TODO: Use cache layers in test
      - name: test
        run: ./gradlew test --continue --no-daemon

      - name: 📊 Publish results with dorny
        if: always()
        uses: dorny/test-reporter@v1.5.0
        with:
          name: 🧬 Test results
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml,.nais/alerts.yml
          VAR: IMAGE_MED_TAG=${{ env.IMAGE_MED_TAG }}
          VARS: .nais/dev.json