name: topics

on:
  push:
    branches:
      - main
    paths:
      - '.nais/topic-*.yml'
      - '.github/workflows/topics.yml'
      - '.nais/dev.yml'
      - '.nais/prod.yml'

jobs:
  deploy:
    strategy:
      matrix:
        name:
          - topic-monade.yml
          - topic-medlem.yml
          - topic-søkere.yml
          - topic-innstilling-11-6.yml
          - topic-arena-sistevedtak.yml
          - topic-manuell-11-2.yml
          - topic-manuell-11-3.yml
          - topic-manuell-11-4.yml
          - topic-manuell-11-5.yml
          - topic-manuell-11-6.yml
          - topic-manuell-11-12.yml
          - topic-manuell-11-19.yml
          - topic-manuell-11-29.yml
          - topic-manuell-22-13.yml
          - topic-kvalitetssikring-11-2.yml
          - topic-kvalitetssikring-11-3.yml
          - topic-kvalitetssikring-11-4.yml
          - topic-kvalitetssikring-11-5.yml
          - topic-kvalitetssikring-11-6.yml
          - topic-kvalitetssikring-11-12.yml
          - topic-kvalitetssikring-11-19.yml
          - topic-kvalitetssikring-11-29.yml
          - topic-kvalitetssikring-22-13.yml
          - topic-inntekter.yml
          - topic-andre-folketrygdytelser.yml
          - topic-iverksettelse-av-vedtak.yml
          - topic-vedtak.yml
          - topic-yrkesskade.yml
        cluster:
          - dev-gcp
          - prod-gcp
        include:
          - cluster: dev-gcp
            vars: dev.yml
          - cluster: prod-gcp
            vars: prod.yml
    name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/${{ matrix.name }}
          VARS: .nais/${{ matrix.vars }}
          PRINT_PAYLOAD: true
