name: Generate UML for topology

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/topology.puml'
      - '.github/workflows/topology.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Topology
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: app:test --tests no.nav.aap.GenerateUML --no-daemon
      - uses: Timmy/plantuml-action@v1
        with:
          args: '-tsvg doc/topology.puml'
      - name: Update doc/topology.svg
        run: |
          git config --local user.name topology
          git config --local user.email topology@users.noreply.github.com
          git add doc/topology.svg
          git remote add topology "https://${{ github.actor }}${{ secrets.PAT }}@github.com/${{ github.repository }}.git"
          git show-ref
          git branch --verbose
          git commit -m "Oppdaterer topology.svg"
          git checkout main
          git pull --rebase topology main
          git push topology main --force-with-lease
