name: Topology UML

on:
  push:
    paths:
      - doc/topology.puml
      - .github/workflows/topology.yml

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: latest
        run: |
          url=https://sourceforge.net/projects/plantuml/best_release.json
          echo "::set-output name=PLANTUML_VERSION::$(curl $url | jq .release.date -r)"

      - uses: actions/cache@v2
        id: cached
        with:
          path: plantuml.jar
          key: ${{ steps.latest.outputs.PLANTUML_VERSION }}

      - if: steps.cached.outputs.cache-hit != 'true'
        run: wget -O plantuml.jar "http://sourceforge.net/projects/plantuml/files/plantuml.jar/download"

      - run: cat doc/topology.puml | java -jar plantuml.jar -svg -pipe > topology.svg

      - uses: actions/upload-artifact@v2
        with:
          path: topology.svg
