name: Generate UML for topology

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/topology.puml'
      - '.github/workflows/topology.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Topology
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: app:test --tests no.nav.aap.GenerateUML --no-daemon

      - uses: Timmy/plantuml-action@v1
        with:
          args: '-tutxt app/build/topology.puml'

      - name: Display diagrams
        run: cat diagrams/*.utxt
