name: Topology UML

on:
  push:
    paths:
      - 'doc/topology.puml'
      - ''.github/workflows/topology.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Timmy/plantuml-action@v1
        with:
          args: '-svg doc/topology.puml'
      - uses: actions/upload-artifact@v2
        with:
          path: doc/topology.svg
