name: Topology UML

on:
  push:
    paths:
      - 'doc/topology.puml'
      - '.github/workflows/topology.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true
      - uses: Timmy/plantuml-action@v1
        with:
          args: '-svg doc/topology.puml'
      - uses: actions/upload-artifact@v2
        with:
          path: doc/topology.svg

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Update Topology.svg
          file_pattern: doc/topology.svg
#          push_options: '--force'
