name: Topology UML

on:
  workflow_run:
    workflows : [ 'Build and Deploy' ]
    types: [ completed ]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 'Build and Deploy'
          run_id: ${{ github.event.workflow_run.id }}
          name: diagram

      - id: latest
        run: |
          url=https://sourceforge.net/projects/plantuml/best_release.json
          echo "::set-output name=PLANTUML_VERSION::$(curl $url | jq .release.date -r)"

      - uses: actions/cache@v2
        id: cached
        with:
          path: plantuml.jar
          key: ${{ steps.latest.outputs.PLANTUML_VERSION }}

      - if: steps.cached.outputs.cache-hit != 'true'
        run: wget -O plantuml.jar "http://sourceforge.net/projects/plantuml/files/plantuml.jar/download"

      - run: cat diagram/topology.puml | java -jar plantuml.jar -svg -pipe > topology.svg

      - uses: actions/upload-artifact@v2
        with:
          path: topology.svg
