name: Generate UML for topology

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/topology.puml'
      - '.github/workflows/topology.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Topology
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: app:test --tests no.nav.aap.GenerateUML --no-daemon
      - uses: Timmy/plantuml-action@v1
        with:
          args: '-tsvg doc/topology.puml'

      - name: Configure Git User
        run: |
          git config --global user.name topology
          git config --global user.email topology@users.noreply.github.com

      - name: Update doc/topology.svg
        run: |
          git add doc/topology.svg
          git commit -m "Oppdaterer topology.svg"
          git push --force-with-lease
